### ISSUE TITLE
component: ListItemCheckbox

### ISSUE THREAD

**Issue by marcopeg** [marcopeg/grocery-list#8]
- show checked / unchecked status
- implement `onChange` callbacl

**Comment by marcopeg** [comment]
```
<ListItemCheckbox
  isChecked={true}
  onChange={(newCheckedState) => {...}} />
```

**Comment by marcopeg** [comment]
The look & feel should be close to Trello checklist items.

![img_2810](https://cloud.githubusercontent.com/assets/427569/14941815/bc533600-0fa9-11e6-99b4-cff83a0266f6.jpg)

**Comment by kzverev** [comment]
@marcopeg Please take a look
